# Generated by Django 3.0.5 on 2020-04-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDoc',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='document.Document')),
                ('source', models.TextField()),
                ('detail', models.TextField()),
                ('modify_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalDoc',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='document.Document')),
                ('version', models.IntegerField()),
                ('running_no', models.IntegerField()),
                ('release_date', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('M', 'Manual'), ('P', 'Procedure'), ('W', 'Work Instruction'), ('F', 'Record Form')], max_length=1)),
                ('status', models.CharField(choices=[('i', 'In-Progress'), ('r', 'Released'), ('o', 'Obsolete')], max_length=1)),
                ('parent_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.InternalDoc')),
            ],
        ),
    ]
