# Generated by Django 3.0.5 on 2020-04-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaldoc',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='internaldoc',
            name='document_id',
        ),
        migrations.AddField(
            model_name='externaldoc',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaldoc',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.Document'),
            preserve_default=False,
        ),
    ]
