# Generated by Django 3.0.5 on 2020-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20200417_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldoc',
            name='status',
            field=models.CharField(choices=[('I', 'In-Progress'), ('R', 'Released'), ('O', 'Obsolete')], max_length=1),
        ),
    ]
