# Generated by Django 3.0.5 on 2020-04-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200417_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldoc',
            name='parent_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.InternalDoc'),
        ),
    ]
