# Generated by Django 3.0.5 on 2020-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200417_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_location',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
