# Generated by Django 3.0.5 on 2020-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200419_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaldoc',
            old_name='status',
            new_name='state',
        ),
    ]
