# Generated by Django 3.0.5 on 2020-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20200419_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldoc',
            name='state',
            field=models.CharField(choices=[('IN', 'In-Progress'), ('RE', 'Released'), ('OB', 'Obsoleted'), ('RC', 'Recalled')], default='IN', max_length=2),
        ),
    ]
