# Generated by Django 3.0.5 on 2020-04-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_remove_employee_role'),
        ('document', '0010_auto_20200421_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldoc',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externaldoc',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Employee'),
        ),
    ]
