# Generated by Django 3.0.5 on 2020-04-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegateuser',
            name='users',
        ),
        migrations.RemoveField(
            model_name='work',
            name='delegate_user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
        migrations.AddField(
            model_name='delegateuser',
            name='employee_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='authen.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegateuser',
            name='work_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='work.Work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authen.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('DCC', 'DCC-review'), ('MR', 'MR-review'), ('VP', 'VP-review'), ('SVP', 'SVP-review'), ('C', 'Completed')], default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('CR', 'Create'), ('E', 'Edit'), ('CA', 'Cancel')], default='CR', max_length=2),
        ),
    ]
