# Generated by Django 3.0.5 on 2020-04-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
        ('work', '0002_auto_20200419_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='employees',
            field=models.ManyToManyField(related_name='works', through='work.DelegateUser', to='authen.Employee'),
        ),
        migrations.AlterField(
            model_name='delegateuser',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Employee'),
        ),
        migrations.AlterField(
            model_name='delegateuser',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Work'),
        ),
    ]
