# Generated by Django 3.0.5 on 2020-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20200419_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='document_id',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='work',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
