# Generated by Django 3.0.5 on 2020-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200419_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
