# Generated by Django 3.0.5 on 2020-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20200420_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateuser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
