# Generated by Django 3.0.5 on 2020-04-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_remove_employee_role'),
        ('work', '0008_delegateuser_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='latest_delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_delegate', to='authen.Employee'),
        ),
    ]
