# Generated by Django 3.0.5 on 2020-04-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20200422_2045'),
        ('work', '0009_work_latest_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='new_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_document', to='document.InternalDoc'),
        ),
    ]
