# Generated by Django 3.0.5 on 2020-04-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lname',
        ),
    ]
