# Generated by Django 3.0.5 on 2020-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20200419_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMP', 'Employee'), ('DCC', 'Document Control Clerk'), ('MR', 'Management Representative'), ('VP', 'Vice President'), ('SVP', 'Senior Vice President')], default='EMP', max_length=3),
        ),
    ]
