# Generated by Django 3.0.5 on 2020-04-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20200419_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
