# Generated by Django 3.0.5 on 2020-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_remove_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='RD', max_length=2),
            preserve_default=False,
        ),
    ]
